import { useState } from 'react'
import { Link } from 'react-router-dom'
import Button from '../../components/common/Button'
import StatusBadge from '../../components/common/StatusBadge'
import { athletes, athleteParticipation, centerProfile, educationPrograms, preventionPrograms, rehabilitationPrograms, teamVisits, teams } from '../../data/center'

function PageHeader({ title, description, action }) { return <div className="page-heading"><div><p className="eyebrow blue-eyebrow">REHABILITATION PLATFORM</p><h2>{title}</h2><p>{description}</p></div>{action}</div> }
function Table({ columns, rows }) { return <div className="table-wrapper"><table><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{columns.map((column) => <td key={column.key}>{column.render ? column.render(row) : row[column.key]}</td>)}</tr>)}</tbody></table></div> }

export function RehabilitationPage() { return <div className="page-container"><PageHeader title="재활관리" description="평가부터 재활, 컨디셔닝, 경기 복귀와 재평가까지 단계별로 관리합니다." /><div className="rehab-flow">{['평가', '재활', '예방', '컨디셔닝', '퍼포먼스', '복귀'].map((item, index) => <div className="flow-step" key={item}><span>0{index + 1}</span><strong>{item}</strong>{index < 5 && <i>→</i>}</div>)}</div><section className="content-section"><Table columns={[{ key: 'name', label: '프로그램' }, { key: 'stage', label: '단계' }, { key: 'description', label: '설명' }, { key: 'status', label: '상태', render: (row) => <StatusBadge status={row.status} /> }, { key: 'manage', label: '관리', render: () => <Button variant="secondary">상세보기</Button> }]} rows={rehabilitationPrograms} /></section></div> }

export function PreventionPage() { return <div className="page-container"><PageHeader title="예방관리" description="부상 전부터 움직임과 위험요소를 평가해 선수의 긴 운동 생명을 관리합니다." /><section className="prevention-message"><div className="symbol-mark small">B</div><div><h3>선수 등록 → 기초 평가 → 위험요소 확인 → 예방 프로그램 → 정기 재평가</h3><p>필요한 재활과 컨디셔닝을 연결해 지속적인 신체관리를 지원합니다.</p></div></section><section className="content-section"><Table columns={[{ key: 'name', label: '평가 프로그램' }, { key: 'focus', label: '평가 항목' }, { key: 'participants', label: '관리 선수' }, { key: 'status', label: '상태', render: (row) => <StatusBadge status={row.status} /> }, { key: 'manage', label: '관리', render: () => <Button variant="secondary">결과 보기</Button> }]} rows={preventionPrograms} /></section></div> }

export function AthletesPage() { const [selected, setSelected] = useState(null); return <div className="page-container"><PageHeader title="선수 목록" description="공개 선수 정보와 종목별 예방·컨디셔닝 콘텐츠를 관리합니다." action={<Button>선수 등록</Button>} /><div className="athlete-grid">{athletes.map((athlete) => <article className="athlete-card" key={athlete.id}><img src={athlete.image} alt={`${athlete.sport} 선수 이미지`} /><div className="athlete-card-body"><div className="promo-meta"><StatusBadge status={athlete.status} /><span>{athlete.sport} · {athlete.position}</span></div><h3>{athlete.name}</h3><p>위험 영역: {athlete.risk}</p><p>{athlete.program}</p><Button variant="secondary" onClick={() => setSelected(athlete)}>평가 리포트</Button></div></article>)}</div>{selected && <section className="content-section athlete-report"><div className="section-header"><div><p className="eyebrow blue-eyebrow">선수 평가 리포트</p><h3>{selected.name} · {selected.sport}</h3></div><Button variant="secondary" onClick={() => setSelected(null)}>닫기</Button></div><div className="score-grid">{[['근력', 82], ['유연성', 74], ['밸런스', 88], ['관절 가동범위', 79], ['코어 안정성', 85], ['움직임', 76]].map(([label, score]) => <div className="score-item" key={label}><span>{label}</span><strong>{score}</strong><div><i style={{ width: `${score}%` }} /></div></div>)}</div><p>과거 부상 및 개인 평가 데이터를 바탕으로 다음 평가일과 권장 프로그램을 연결합니다.</p></section>}</div> }

export function TeamsPage() { return <div className="page-container"><PageHeader title="팀 / 단체 관리" description="학교팀, 대학팀, 실업팀과 스포츠클럽을 조직 단위로 관리합니다." action={<Button>팀 등록</Button>} /><div className="team-card-grid">{teams.map((team) => <article className="team-card" key={team.id}><div className="team-card-heading"><div className="symbol-mark small">B</div><div><h3>{team.name}</h3><span>{team.type} · 등록 선수 {team.athletes}명</span></div></div><div className="team-status-row"><span>정상 <strong>{team.normal}</strong></span><span>관찰 <strong>{team.observe}</strong></span><span>재활 <strong>{team.rehab}</strong></span><span>집중 <strong>{team.intensive}</strong></span></div><p>다음 재평가 {team.next}</p><Button variant="secondary">팀 상세보기</Button></article>)}</div></div> }

export function TeamVisitPage() { return <div className="page-container"><PageHeader title="팀 예약 현황" description="팀이 예약한 평가와 방문 프로그램, 담당 전문가 일정을 관리합니다." action={<Button>예약 등록</Button>} /><section className="content-section"><Table columns={[{ key: 'team', label: '팀명' }, { key: 'date', label: '예약일' }, { key: 'time', label: '예약 시간' }, { key: 'program', label: '프로그램' }, { key: 'expert', label: '담당 전문가' }, { key: 'status', label: '예약 상태', render: (row) => <StatusBadge status={row.status} /> }, { key: 'visited', label: '방문 여부' }]} rows={teamVisits} /></section></div> }

export function AthleteParticipationPage() { return <div className="page-container"><PageHeader title="유명선수 참가 목록" description="센터 프로그램과 공개 콘텐츠에 참여하는 선수 목록을 관리합니다." action={<Button>참가 등록</Button>} /><section className="content-section"><Table columns={[{ key: 'athlete', label: '선수명' }, { key: 'sport', label: '종목' }, { key: 'program', label: '참가 프로그램' }, { key: 'date', label: '참가일' }, { key: 'status', label: '참가 상태', render: (row) => <StatusBadge status={row.status} /> }, { key: 'content', label: '콘텐츠' }, { key: 'note', label: '메모' }, { key: 'manage', label: '관리', render: () => <Button variant="secondary">상세보기</Button> }]} rows={athleteParticipation} /></section></div> }

export function EducationPage() { return <div className="page-container"><PageHeader title="교육 / 연구협력" description="재활학과, 물리치료, 운동처방, 스포츠과학 학생과 현장을 연결합니다." action={<Button>프로그램 등록</Button>} /><div className="education-highlight"><strong>현장실습 · 인턴십 · 연구 프로젝트 · 세미나 · 멘토링</strong><span>재활 현장과 연계해 전문성을 키우는 교육 공간</span></div><section className="content-section"><Table columns={[{ key: 'university', label: '협력 대학' }, { key: 'program', label: '프로그램' }, { key: 'students', label: '참여 학생' }, { key: 'projects', label: '진행 프로젝트' }, { key: 'status', label: '상태', render: (row) => <StatusBadge status={row.status} /> }]} rows={educationPrograms} /></section></div> }

export function CenterInfoPage() { return <div className="page-container"><PageHeader title="센터 소개" description="선수의 회복을 넘어, 선수의 미래까지 관리합니다." /><section className="center-intro"><div className="symbol-mark">B</div><div><p className="eyebrow blue-eyebrow">REHABILITATION · PREVENTION · PERFORMANCE</p><h2>{centerProfile.name}</h2><p>우리는 부상 이후의 재활만 제공하는 곳이 아닙니다. 선수의 신체 상태를 전문적으로 평가하고 부상 위험을 사전에 확인하며 재활, 예방관리, 컨디셔닝까지 지속적으로 관리합니다.</p><div className="center-pill-list">{['스포츠 재활', '일반 재활', '수술 후 재활', '기능 회복', '움직임 평가', '부상 위험 평가', '예방관리', '컨디셔닝', '경기 복귀', '장기 관리'].map((item) => <span key={item}>{item}</span>)}</div></div></section><section className="content-section intro-copy"><h3>평가에서 선수 생명 관리까지</h3><p>선수는 종목, 포지션, 훈련량, 경기 일정과 반복 동작에 따라 신체에 요구되는 조건이 다릅니다. 통증이 발생한 부위만 보는 대신 평가 → 분석 → 재활 → 예방 → 컨디셔닝 → 재평가의 연속 시스템으로 관리합니다.</p><p>다친 이후에만 찾아오는 곳이 아닙니다. 움직임과 신체 상태를 미리 평가하고 약한 부분을 파악해 훈련을 조정합니다. 목표는 선수가 더 오래 운동하고 경기력을 유지하도록 돕는 것입니다.</p><h3>팀과 대학을 연결하는 전문 인력</h3><p>의료진, 재활 전문가, 물리치료사, 운동처방 전문가, 스포츠 컨디셔닝 전문가, 연구 인력이 협력합니다. 중·고·대학교 팀과 함께 방문 평가, 선수별 결과, 팀 리포트, 예방 프로그램, 정기 재평가를 운영하며 재활학과·물리치료·운동처방·스포츠과학 학생에게 현장실습, 인턴십, 연구, 세미나, 멘토링 기회를 제공합니다.</p></section></div> }

export function CenterOverviewPage() { return <div className="page-container"><PageHeader title="전체 현황" description="재활과 예방, 선수와 팀, 교육과 협력 네트워크를 한 화면에서 확인합니다." /><div className="summary-grid center-summary">{[{ label: '관리 선수', value: 186 }, { label: '등록 팀', value: 12 }, { label: '재활 프로그램', value: rehabilitationPrograms.length }, { label: '예방 평가', value: preventionPrograms.length }, { label: '교육 협력', value: educationPrograms.length }, { label: '찾아가는 평가', value: teamVisits.length }].map((item) => <div className="summary-card" key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div><section className="content-section"><div className="section-header"><h3>관리 흐름</h3><Link className="text-link" to="/rehabilitation">재활관리로 이동</Link></div><div className="rehab-flow">{['평가', '재활', '예방', '컨디셔닝', '퍼포먼스', '교육·연구'].map((item, index) => <div className="flow-step" key={item}><span>0{index + 1}</span><strong>{item}</strong></div>)}</div></section></div> }
