import { useState } from 'react'
import Button from '../../components/common/Button'
import Modal from '../../components/common/Modal'
import StatusBadge from '../../components/common/StatusBadge'
import { celebrityCases, memberships, mediaItems, members, partnerHospitals, partnerOrganizations, sports } from '../../data/extended'

function PageHeader({ title, description, action }) { return <div className="page-heading"><div><p className="eyebrow blue-eyebrow">SPORTS MEDICINE ADMIN</p><h2>{title}</h2><p>{description}</p></div>{action}</div> }
function DataTable({ columns, rows, onDelete }) { return <div className="table-wrapper"><table><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}{onDelete && <th>관리</th>}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{columns.map((column) => <td key={column.key}>{column.render ? column.render(row) : row[column.key]}</td>)}{onDelete && <td><Button variant="danger" onClick={() => onDelete(row.id)}>삭제</Button></td>}</tr>)}</tbody></table></div> }

export function MembersPage() {
  const [items, setItems] = useState(members); const [query, setQuery] = useState(''); const [type, setType] = useState('전체'); const [selected, setSelected] = useState(null)
  const filtered = items.filter((item) => (item.name.includes(query) || item.id.includes(query)) && (type === '전체' || item.type === type))
  return <div className="page-container"><PageHeader title="회원 / 멤버십 관리" description="회원 정보와 멤버십 등급을 관리합니다." action={<Button>회원 등록</Button>} /><div className="summary-grid compact-summary"><div className="summary-card"><span>전체 회원</span><strong>{items.length}</strong></div><div className="summary-card"><span>정상 회원</span><strong>{items.filter((item) => item.status === '정상').length}</strong></div><div className="summary-card"><span>멤버십 등급</span><strong>{memberships.length}</strong></div></div><section className="content-section"><div className="toolbar"><input className="inline-input" placeholder="이름 또는 회원번호 검색" value={query} onChange={(event) => setQuery(event.target.value)} /><select value={type} onChange={(event) => setType(event.target.value)}><option>전체</option>{['일반회원', '스포츠회원', '선수회원', 'VIP', '협력기관 회원'].map((item) => <option key={item}>{item}</option>)}</select></div><DataTable columns={[{ key: 'id', label: '회원번호' }, { key: 'name', label: '이름' }, { key: 'phone', label: '연락처' }, { key: 'type', label: '회원 유형' }, { key: 'lastVisit', label: '최근 방문일' }, { key: 'reservations', label: '예약 횟수' }, { key: 'status', label: '상태', render: (row) => <StatusBadge status={row.status} /> }, { key: 'detail', label: '상세', render: (row) => <Button variant="secondary" onClick={() => setSelected(row)}>보기</Button> }]} rows={filtered} onDelete={(id) => setItems((current) => current.filter((item) => item.id !== id))} /></section><section className="content-section"><div className="section-header"><h3>멤버십 등급</h3></div><DataTable columns={[{ key: 'name', label: '등급명' }, { key: 'description', label: '설명' }, { key: 'benefit', label: '회원 혜택' }, { key: 'discount', label: '할인율' }, { key: 'priority', label: '예약 우선권' }, { key: 'enabled', label: '사용 여부', render: (row) => <StatusBadge status={row.enabled ? '사용중' : '중지'} /> }]} rows={memberships.map((item, index) => ({ ...item, id: index }))} /></section><Modal isOpen={Boolean(selected)} title="회원 상세보기" onClose={() => setSelected(null)}>{selected && <div className="detail-list"><strong>{selected.name} ({selected.id})</strong><span>{selected.phone}</span><span>{selected.type} · {selected.status}</span><span>가입일 {selected.joinedAt}</span><Button onClick={() => setSelected(null)}>확인</Button></div>}</Modal></div>
}

export function SportsPage() { const [selected, setSelected] = useState(sports[0]); return <div className="page-container"><PageHeader title="스포츠 전문 분야" description="스포츠 종목과 담당 전문의를 유연하게 연결합니다." /><div className="sports-layout"><section className="content-section sport-list">{sports.map((sport) => <button key={sport.id} type="button" className={`sport-row ${selected.id === sport.id ? 'selected' : ''}`} onClick={() => setSelected(sport)}><span>{sport.name}</span><strong>{sport.doctors.length}명</strong></button>)}</section><section className="content-section sport-detail"><p className="eyebrow blue-eyebrow">SPORTS SPECIALTY</p><h2>{selected.name}</h2><h3>스포츠 손상 전문 영역</h3><div className="tag-list">{selected.specialties.map((item) => <span key={item}>{item}</span>)}</div><h3>담당 전문의</h3><div className="doctor-grid">{selected.doctors.map((doctor) => <div className="doctor-card" key={doctor.name}><div className="avatar-placeholder">{doctor.name.slice(0, 1)}</div><div className="doctor-card-body"><strong>{doctor.name}</strong><small>{doctor.title}</small><Button variant="secondary">상세보기</Button></div></div>)}</div></section></div></div> }

export function CelebritiesPage() { return <GenericContentPage title="유명인 / 선수" description="공개 선수 정보와 종목별 예방·컨디셔닝 콘텐츠를 관리합니다." items={celebrityCases} columns={[{ key: 'name', label: '이름' }, { key: 'sport', label: '스포츠 종목' }, { key: 'title', label: '콘텐츠 제목' }, { key: 'type', label: '사례 유형' }, { key: 'period', label: '활동 시기' }, { key: 'visible', label: '공개 여부', render: (row) => <StatusBadge status={row.visible ? '공개' : '비공개'} /> }]} /> }
export function MediaPage() { return <GenericContentPage title="언론 / 뉴스 관리" description="의료진의 공개 기사, 인터뷰, 방송 콘텐츠를 관리합니다." items={mediaItems} columns={[{ key: 'title', label: '제목' }, { key: 'doctor', label: '의료진' }, { key: 'outlet', label: '매체명' }, { key: 'type', label: '유형' }, { key: 'date', label: '게시일' }, { key: 'visible', label: '공개 여부', render: (row) => <StatusBadge status={row.visible ? '공개' : '비공개'} /> }]} /> }
export function PartnerPage({ organization = false }) { const source = organization ? partnerOrganizations : partnerHospitals; return <GenericContentPage title={organization ? '협력 기관' : '협력 병원'} description="협력 네트워크 정보를 관리합니다." items={source} columns={[{ key: 'name', label: organization ? '기관명' : '병원명' }, { key: organization ? 'type' : 'region', label: organization ? '기관 유형' : '지역' }, { key: 'cooperation', label: '협력 분야' }, { key: 'contact', label: '담당자' }, { key: 'phone', label: '연락처' }, { key: 'status', label: '상태', render: (row) => <StatusBadge status={row.status} /> }]} /> }
function GenericContentPage({ title, description, items, columns }) { const [rows, setRows] = useState(items); const [query, setQuery] = useState(''); const [selected, setSelected] = useState('전체'); const statusOptions = [...new Set(items.map((item) => item.status).filter(Boolean))]; const filtered = rows.filter((row) => Object.values(row).some((value) => String(value).includes(query)) && (selected === '전체' || row.status === selected)); return <div className="page-container"><PageHeader title={title} description={description} action={<Button>새로 등록</Button>} /><section className="content-section"><div className="toolbar"><input className="inline-input" placeholder="키워드 검색" value={query} onChange={(event) => setQuery(event.target.value)} />{statusOptions.length > 0 && <select value={selected} onChange={(event) => setSelected(event.target.value)}><option>전체</option>{statusOptions.map((item) => <option key={item}>{item}</option>)}</select>}</div><DataTable columns={columns} rows={filtered} onDelete={(id) => setRows((current) => current.filter((item) => item.id !== id))} /></section></div> }